/**
 * Known arity ranges for TinyMUX / RhostMUSH built-in functions.
 * [minArgs, maxArgs] — use Infinity for unlimited upper bound.
 *
 * Only strictly-bounded functions are listed.  Omitting a function means the
 * arg-count rule skips it entirely (no false positives for unknown functions).
 */
export const ARITIES: Readonly<Record<string, [number, number]>> = {
  // Arithmetic
  add:     [1, Infinity],
  sub:     [1, Infinity],
  mul:     [1, Infinity],
  div:     [2, 2],
  mod:     [2, 2],
  abs:     [1, 1],
  sign:    [1, 1],
  log:     [1, 2],
  ln:      [1, 1],
  exp:     [1, 1],
  sin:     [1, 1],
  cos:     [1, 1],
  tan:     [1, 1],
  atan:    [1, 2],
  pi:      [0, 0],
  e:       [0, 0],
  bound:   [3, 3],
  between: [3, 3],
  fdiv:    [2, 2],
  fmod:    [2, 2],
  trunc:   [1, 1],
  inc:     [1, 1],
  dec:     [1, 1],
  // Comparison
  eq:      [2, 2],
  neq:     [2, 2],
  gt:      [2, 2],
  gte:     [2, 2],
  lt:      [2, 2],
  lte:     [2, 2],
  // Logic
  and:     [1, Infinity],
  or:      [1, Infinity],
  not:     [1, 1],
  // Control flow
  if:      [2, 3],
  ifelse:  [3, 3],
  switch:  [3, Infinity],
  // Registers
  setq:    [2, 2],
  r:       [1, 1],
  // Iteration
  iter:    [2, 4],
  map:     [2, 4],
  filter:  [2, 4],
  ilist:   [1, 3],
  fold:    [2, 4],
  munge:   [3, 4],
  // Object / attribute
  name:    [1, 1],
  loc:     [1, 1],
  get:     [1, 1],
  set:     [2, 2],
  v:       [1, 1],
  u:       [1, Infinity],
  hasflag: [2, 2],
  hasattr: [2, 2],
  isnum:   [1, 1],
  isdbref: [1, 1],
  null:    [0, Infinity],
  noop:    [0, Infinity],
  pmatch:  [1, 1],
  lparent: [1, 1],
  hastype: [2, 2],
  // String
  strlen:   [1, 1],
  mid:      [3, 3],
  left:     [2, 2],
  right:    [2, 2],
  trim:     [1, 3],
  ljust:    [2, 3],
  rjust:    [2, 3],
  center:   [2, 3],
  repeat:   [2, 2],
  reverse:  [1, 1],
  scramble: [1, 1],
  encrypt:  [2, 2],
  decrypt:  [2, 2],
  comp:     [2, 2],
  streq:    [2, 2],
  cat:      [2, Infinity],
  index:    [3, 4],
  setinter: [2, 3],
  setunion: [2, 3],
  setdiff:  [2, 3],
  // List / matching
  words:    [1, 2],
  match:    [2, 3],
  matchall: [2, 3],
  lcon:     [1, 2],
  lwho:     [0, 1],
  revwords: [1, 2],
  sort:     [1, 4],
  lsort:    [1, 4],
  sortby:   [2, 3],
  unique:   [1, 2],
  shuffle:  [1, 2],
  extract:  [3, 5],
  ldelete:  [2, 4],
  replace:  [3, 5],
  insert:   [3, 5],
  grab:     [2, 3],
  graball:  [2, 3],
  member:   [2, 3],
  lpos:     [2, 3],
  // Formatting
  ansi:    [2, Infinity],
  // Tags (RhostMUSH)
  tag:         [1, 1],
  listtags:    [0, 1],
  tagmatch:    [1, 1],
};
